### ISSUE TITLE
Release 1.2.0?

### ISSUE THREAD

**Issue by joshbranham** [jswanner/private_attr#10]
This commit landed https://github.com/jswanner/private_attr/commit/52211cd5f11f79b8f782e22aca2cdbbe21151f7e which was in effort to remove a fork we run. Unfortunately a new version has not been released since and we are still on our internal fork. Is there anyway to release a new version with that commit as mentioned in https://github.com/jswanner/private_attr/pull/8#issuecomment-222233491?

**Comment by jswanner** [comment]
Whoa, blast for the past... I just released a new version.

**Comment by joshbranham** [comment]
Thank you!

**Comment by sordu** [comment]
@jswanner Hey there, thanks a lot for your work and the new release. I was wondering why you bumped the major version. Are there any breaking changes, other than dependencies?

**Comment by joshbranham** [comment]
Here is the diff from the last release to the new https://github.com/jswanner/private_attr/compare/8f1e2dbb085b384b9cd46bd5a9094ba832fc1c9a..7c60e040b13cfa32117e21c05071df4151587096

**Comment by sordu** [comment]
Thank you!

**Comment by jswanner** [comment]
It shouldn't have been a major version bump, it was a mistake I made in haste.
